# Generated by Django 5.0.3 on 2024-03-30 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='employe_images/')),
                ('phone', models.CharField(max_length=12)),
                ('join_date', models.DateField(null=True)),
                ('developer', models.CharField(choices=[('frontend Developer', 'frontend Developer'), ('backend Developer', 'backend Developer'), ('java Developer', 'java Developer'), ('Python Developer', 'Python Developer'), ('php Developer', 'php Developer'), ('graphic designer', 'graphic designer'), ('fullstack Developer', 'fullstack Developer'), ('Technical Leader', 'Technical Leader'), ('Associate Software Engineer', 'Associate Software Engineer'), ('consulting python Developer', 'consulting python Developer'), ('Junior Software Engineer', 'Junior Software Engineer'), ('Senior Ui/Ux Designer', 'Senior Ui/Ux Designer'), ('Technical Director', 'Technical Director')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('start_date', models.DateField(null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('reason', models.TextField()),
                ('employ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.employ')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=6)),
                ('employ', models.ManyToManyField(to='employe.employ')),
            ],
        ),
    ]
